
export const SOIL_MASTER_DATA = [
  {
    "soil_id": "alluvial_soil",
    "soil_name": "Alluvial Soil",
    "category": "Primary",
    "regions_in_india": ["Punjab","Haryana","Uttar Pradesh","Bihar","West Bengal","Assam","Odisha","Andhra Pradesh","Telangana"],
    "texture": ["Sandy Loam","Loam","Clay Loam"],
    "color": ["Light Grey","Ash Grey","Brown"],
    "ph_range": "6.5 - 8.0",
    "water_retention": "Medium",
    "drainage": "Good",
    "nutrient_profile": {
      "nitrogen": "Low",
      "phosphorus": "Medium",
      "potassium": "Medium",
      "zinc": "Low-Medium",
      "iron": "Medium",
      "sulphur": "Low",
      "boron": "Low",
      "manganese": "Medium"
    },
    "organic_matter": "Medium",
    "fertility": "High",
    "compaction_tendency": "Low-Medium",
    "ec_range": "0.2 - 1.0",
    "cec": "Medium",
    "common_crops": ["Paddy","Wheat","Sugarcane","Maize","Pulses","Oilseeds","Vegetables","Fruits"],
    "major_problems": ["Nitrogen deficiency","Zinc deficiency in some areas"],
    "management_practices": [
      "Add organic manure",
      "Split nitrogen application",
      "Apply zinc sulphate if deficient",
      "Green manuring between seasons"
    ],
    "suitable_seasons": ["Kharif","Rabi"]
  },
  {
    "soil_id": "black_soil",
    "soil_name": "Black Soil (Regur)",
    "category": "Primary",
    "regions_in_india": ["Maharashtra","Madhya Pradesh","Telangana","Karnataka","Gujarat","Andhra Pradesh","Rajasthan"],
    "texture": ["Clayey","Clay Loam"],
    "color": ["Deep Black","Dark Brown"],
    "ph_range": "7.5 - 8.5",
    "water_retention": "Very High",
    "drainage": "Poor",
    "nutrient_profile": {
      "nitrogen": "Low",
      "phosphorus": "Low",
      "potassium": "High",
      "zinc": "Low",
      "iron": "Medium",
      "sulphur": "Medium",
      "boron": "Low",
      "manganese": "Low-Medium"
    },
    "organic_matter": "Medium",
    "fertility": "High",
    "compaction_tendency": "High",
    "ec_range": "0.5 - 2.0",
    "cec": "High",
    "common_crops": ["Cotton","Soybean","Groundnut","Sorghum","Wheat","Sunflower","Safflower"],
    "major_problems": ["Waterlogging","Soil cracking","Difficult to work when wet","Zinc deficiency"],
    "management_practices": [
      "Avoid excess irrigation",
      "Use organic compost",
      "Deep ploughing before monsoon",
      "Broad bed and furrow system",
      "Apply zinc and boron"
    ],
    "suitable_seasons": ["Kharif","Rabi"]
  },
  {
    "soil_id": "red_soil",
    "soil_name": "Red Soil",
    "category": "Primary",
    "regions_in_india": ["Tamil Nadu","Karnataka","Andhra Pradesh","Odisha","Chhattisgarh","Jharkhand","Telangana","Maharashtra"],
    "texture": ["Sandy","Loamy","Sandy Loam"],
    "color": ["Red","Reddish Brown","Yellowish Brown"],
    "ph_range": "5.5 - 7.0",
    "water_retention": "Low",
    "drainage": "Good",
    "nutrient_profile": {
      "nitrogen": "Low",
      "phosphorus": "Low",
      "potassium": "Low",
      "zinc": "Low",
      "iron": "High",
      "sulphur": "Low",
      "boron": "Low",
      "manganese": "Medium-High"
    },
    "organic_matter": "Low",
    "fertility": "Low to Medium",
    "compaction_tendency": "Low",
    "ec_range": "0.1 - 0.5",
    "cec": "Low",
    "common_crops": ["Millets","Pulses","Groundnut","Cotton","Tobacco","Potato"],
    "major_problems": ["Low fertility","Low organic matter","Phosphorus fixation","Erosion susceptibility"],
    "management_practices": [
      "Add farmyard manure",
      "Use balanced fertilizers",
      "Apply lime in acidic areas",
      "Mulching to reduce erosion",
      "Green manure crops"
    ],
    "suitable_seasons": ["Kharif"]
  },
  {
    "soil_id": "laterite_soil",
    "soil_name": "Laterite Soil",
    "category": "Primary",
    "regions_in_india": ["Kerala","Goa","Karnataka","Maharashtra","Assam","Meghalaya","Tamil Nadu"],
    "texture": ["Coarse","Porous","Sandy Loam"],
    "color": ["Red","Brown","Yellowish Red"],
    "ph_range": "4.5 - 6.5",
    "water_retention": "Low",
    "drainage": "Very Good",
    "nutrient_profile": {
      "nitrogen": "Low",
      "phosphorus": "Low",
      "potassium": "Low",
      "zinc": "Low",
      "iron": "Very High",
      "sulphur": "Low",
      "boron": "Low",
      "manganese": "High"
    },
    "organic_matter": "Low",
    "fertility": "Low",
    "compaction_tendency": "Medium",
    "ec_range": "0.1 - 0.4",
    "cec": "Low",
    "common_crops": ["Tea","Coffee","Cashew","Rubber","Coconut","Pepper"],
    "major_problems": ["Leaching of nutrients","High acidity","Iron and aluminium toxicity","Low nutrient retention"],
    "management_practices": [
      "Mulching",
      "Organic matter enrichment",
      "Lime application",
      "Use of rock phosphate",
      "Composting"
    ],
    "suitable_seasons": ["Perennial Crops"]
  },
  {
    "soil_id": "arid_soil",
    "soil_name": "Arid / Desert Soil",
    "category": "Primary",
    "regions_in_india": ["Rajasthan","Gujarat","Haryana","Punjab"],
    "texture": ["Sandy","Sandy Loam"],
    "color": ["Light Brown","Yellow","Pale Brown"],
    "ph_range": "7.0 - 8.5",
    "water_retention": "Very Low",
    "drainage": "Excessive",
    "nutrient_profile": {
      "nitrogen": "Very Low",
      "phosphorus": "Low",
      "potassium": "Low-Medium",
      "zinc": "Low",
      "iron": "Low",
      "sulphur": "Low",
      "boron": "Medium",
      "manganese": "Low"
    },
    "organic_matter": "Very Low",
    "fertility": "Very Low",
    "compaction_tendency": "Low",
    "ec_range": "0.5 - 3.0",
    "cec": "Very Low",
    "common_crops": ["Bajra","Guar","Moong","Moth Bean","Cluster Bean"],
    "major_problems": ["Moisture stress","Wind erosion","Low organic matter","Salinity in some areas"],
    "management_practices": [
      "Drip irrigation",
      "Organic mulching",
      "Windbreaks and shelter belts",
      "Frequent small doses of fertilizer",
      "Sand dune stabilization"
    ],
    "suitable_seasons": ["Kharif"]
  },
  {
    "soil_id": "mountain_forest_soil",
    "soil_name": "Mountain / Forest Soil",
    "category": "Primary",
    "regions_in_india": ["Himachal Pradesh","Uttarakhand","Jammu & Kashmir","Sikkim","Arunachal Pradesh","Nagaland","Mizoram"],
    "texture": ["Loamy","Silty","Silt Loam"],
    "color": ["Brown","Dark Brown","Dark"],
    "ph_range": "5.0 - 6.5",
    "water_retention": "Medium",
    "drainage": "Good",
    "nutrient_profile": {
      "nitrogen": "Medium",
      "phosphorus": "Low",
      "potassium": "Medium",
      "zinc": "Medium",
      "iron": "Medium-High",
      "sulphur": "Medium",
      "boron": "Low-Medium",
      "manganese": "Medium"
    },
    "organic_matter": "High",
    "fertility": "Medium",
    "compaction_tendency": "Low",
    "ec_range": "0.1 - 0.5",
    "cec": "Medium-High",
    "common_crops": ["Apple","Maize","Barley","Potato","Tea","Cardamom","Ginger"],
    "major_problems": ["Soil erosion","Acidic pH","Phosphorus deficiency","Steep slopes"],
    "management_practices": [
      "Terrace farming",
      "Contour ploughing",
      "Cover crops",
      "Rock phosphate application",
      "Lime in acidic areas"
    ],
    "suitable_seasons": ["Rabi","Kharif"]
  },
  {
    "soil_id": "saline_soil",
    "soil_name": "Saline Soil",
    "category": "Problematic",
    "regions_in_india": ["Gujarat","Rajasthan","Punjab","Haryana","Coastal Areas","Uttar Pradesh"],
    "texture": ["Clayey","Loamy","Clay Loam"],
    "color": ["Grey","White Crust","Brownish Grey"],
    "ph_range": "8.0 - 10.0",
    "water_retention": "Poor",
    "drainage": "Poor",
    "nutrient_profile": {
      "nitrogen": "Low",
      "phosphorus": "Low",
      "potassium": "Medium",
      "zinc": "Low",
      "iron": "Low",
      "sulphur": "Medium-High",
      "boron": "High",
      "manganese": "Low"
    },
    "organic_matter": "Low",
    "fertility": "Low",
    "compaction_tendency": "High",
    "ec_range": "4.0 - 16.0",
    "cec": "Medium",
    "common_crops": ["Barley","Salt-tolerant Paddy","Berseem","Dhaincha"],
    "major_problems": ["Salt accumulation","Poor structure","Toxicity to plants","Reduced water uptake"],
    "management_practices": [
      "Gypsum application",
      "Proper drainage",
      "Leaching with fresh water",
      "Salt-tolerant crop varieties",
      "Raised bed planting"
    ],
    "suitable_seasons": ["Rabi"]
  },
  {
    "soil_id": "alkaline_soil",
    "soil_name": "Alkaline Soil",
    "category": "Problematic",
    "regions_in_india": ["Uttar Pradesh","Punjab","Haryana","Bihar"],
    "texture": ["Clayey","Clay Loam","Loamy"],
    "color": ["Grey","Whitish","Pale Brown"],
    "ph_range": "8.5 - 10.5",
    "water_retention": "Medium",
    "drainage": "Poor",
    "nutrient_profile": {
      "nitrogen": "Low",
      "phosphorus": "Very Low",
      "potassium": "Medium",
      "zinc": "Very Low",
      "iron": "Very Low",
      "sulphur": "Low",
      "boron": "High",
      "manganese": "Very Low"
    },
    "organic_matter": "Low",
    "fertility": "Low",
    "compaction_tendency": "High",
    "ec_range": "2.0 - 8.0",
    "cec": "Medium",
    "common_crops": ["Rice","Wheat (with treatment)","Dhaincha","Berseem"],
    "major_problems": ["High sodium","Micronutrient deficiency","Poor physical condition","Dispersion of clay"],
    "management_practices": [
      "Add organic matter",
      "Use sulfur-based amendments",
      "Gypsum application",
      "Green manuring with dhaincha",
      "Apply FeSO4 and ZnSO4"
    ],
    "suitable_seasons": ["Rabi","Kharif"]
  },
  {
    "soil_id": "peaty_marshy_soil",
    "soil_name": "Peaty & Marshy Soil",
    "category": "Problematic",
    "regions_in_india": ["Kerala","West Bengal","Odisha","Sundarbans","North Bihar"],
    "texture": ["Clayey","Muck","Organic"],
    "color": ["Dark Brown","Black","Bluish Black"],
    "ph_range": "4.0 - 6.0",
    "organic_matter": "Very High",
    "water_retention": "Very High",
    "drainage": "Very Poor",
    "nutrient_profile": {
      "nitrogen": "Medium-High",
      "phosphorus": "Low",
      "potassium": "Low",
      "zinc": "Low",
      "iron": "High",
      "sulphur": "High",
      "boron": "Low",
      "manganese": "High"
    },
    "fertility": "Medium",
    "compaction_tendency": "Very Low",
    "ec_range": "1.0 - 4.0",
    "cec": "Very High",
    "common_crops": ["Paddy","Jute","Coconut"],
    "major_problems": ["Poor drainage","Waterlogging","High acidity","Iron toxicity"],
    "management_practices": [
      "Drainage channels",
      "Raised bed farming",
      "Lime application",
      "Ridge and furrow planting",
      "Phosphate fertilizers"
    ],
    "suitable_seasons": ["Kharif"]
  },
  {
    "soil_id": "coastal_sandy_soil",
    "soil_name": "Coastal Sandy Soil",
    "category": "Problematic",
    "regions_in_india": ["Tamil Nadu Coast","Kerala Coast","Odisha Coast","Andhra Coast","West Bengal Coast","Goa Coast"],
    "texture": ["Sandy","Sandy Loam"],
    "color": ["Light Grey","Sandy White","Yellowish"],
    "ph_range": "7.0 - 8.5",
    "water_retention": "Very Low",
    "drainage": "Excessive",
    "nutrient_profile": {
      "nitrogen": "Very Low",
      "phosphorus": "Low",
      "potassium": "Low",
      "zinc": "Low",
      "iron": "Low",
      "sulphur": "Medium",
      "boron": "Medium-High",
      "manganese": "Low"
    },
    "organic_matter": "Very Low",
    "fertility": "Low",
    "salinity_risk": "High",
    "compaction_tendency": "Very Low",
    "ec_range": "2.0 - 8.0",
    "cec": "Very Low",
    "common_crops": ["Coconut","Casuarina","Cashew","Prawns"],
    "major_problems": ["Salt spray","Wind erosion","Very poor nutrient retention","Salinity intrusion"],
    "management_practices": [
      "Organic compost",
      "Windbreaks",
      "Salt-tolerant varieties",
      "Coir pith application",
      "Drip irrigation with fresh water"
    ],
    "suitable_seasons": ["Year-round with irrigation"]
  }
];
