/**
 * MILA - Advanced Farm & Crop Management Types
 * Comprehensive type definitions for farm operations, scouting, and crop lifecycle
 */

// ============= FIELD MANAGEMENT (B1) =============

export interface FieldBoundary {
  type: 'polygon' | 'circle' | 'rectangle';
  coordinates: { lat: number; lng: number }[];
  area?: number; // Auto-calculated in hectares
  center?: { lat: number; lng: number };
}

export interface CropHistoryEntry {
  id: string;
  cropType: string;
  variety?: string;
  sowingDate: string;
  harvestDate?: string;
  yield?: number; // kg/hectare
  quality?: 'A' | 'B' | 'C';
  profitability?: number; // INR/hectare
  notes?: string;
}

export interface FieldHealthMetrics {
  overallScore: number; // 0-100
  soilHealth: number; // 0-100
  cropPerformance: number; // 0-100
  pestPressure: number; // 0-100 (lower is better)
  waterManagement: number; // 0-100
  lastUpdated: string;
  trend: 'improving' | 'stable' | 'declining';
}

export interface EnhancedField {
  id: string;
  name: string;
  size: number;
  sizeUnit: 'acres' | 'hectares';
  boundary?: FieldBoundary;
  currentCrop?: string;
  soilType: string;
  irrigationType: string;
  location?: string;
  cropHistory: CropHistoryEntry[];
  healthMetrics?: FieldHealthMetrics;
  isActive: boolean;
  image_url?: string;
  createdAt: string;
  updatedAt: string;
}

// ============= CROP LIFECYCLE TRACKING (B2) =============

export interface CropStage {
  name: string;
  startDay: number; // Calendar-based
  endDay: number;
  startGDD?: number; // Growing Degree Days
  endGDD?: number;
  description: string;
  criticalTasks: string[];
  riskFactors: string[];
}

export interface GrowingDegreeDayConfig {
  baseTemp: number; // Base temperature (°C)
  maxTemp: number; // Maximum effective temperature (°C)
  accumulatedGDD: number; // Current accumulated GDD
  requiredGDD: number; // Total GDD required for maturity
}

export interface CropLifecycleTracking {
  id: string;
  fieldId: string;
  cropType: string;
  variety: string;
  sowingDate: string;
  currentStage: string;
  stageMethod: 'calendar' | 'gdd' | 'manual';
  daysFromSowing: number;
  gddConfig?: GrowingDegreeDayConfig;
  stages: CropStage[];
  manualOverride?: {
    stage: string;
    reason: string;
    overriddenAt: string;
  };
  expectedHarvestDate: string;
  actualHarvestDate?: string;
}

// ============= TASK ENGINE (B3) =============

export type TaskType =
  | 'irrigation'
  | 'fertilizer'
  | 'pesticide'
  | 'weeding'
  | 'scouting'
  | 'harvest'
  | 'post-harvest'
  | 'soil-test'
  | 'spray-safety'
  | 'market-check'
  | 'land-preparation'
  | 'sowing';

export type TaskPriority = 'critical' | 'high' | 'medium' | 'low';
export type TaskStatus = 'pending' | 'in-progress' | 'completed' | 'skipped' | 'overdue';

export interface RecurrencePattern {
  type: 'daily' | 'weekly' | 'interval' | 'stage-based';
  interval?: number; // For interval-based (e.g., every 3 days)
  endCondition?: 'date' | 'stage' | 'manual';
  endDate?: string;
  endStage?: string;
}

export interface TaskInstruction {
  step: number;
  description: string;
  warning?: string;
  imageUrl?: string;
}

export interface EnhancedTask {
  id: string;
  fieldId: string;
  cropId?: string;
  type: TaskType;
  title: string;
  description: string;
  whyItMatters: string;
  howTo: TaskInstruction[];
  priority: TaskPriority;
  status: TaskStatus;
  dueDate: string;
  estimatedCost?: number;
  estimatedTime?: number; // in hours
  safetyPrecautions?: string[];
  recurrence?: RecurrencePattern;
  dependencies?: string[]; // Task IDs that must be completed first
  weatherDependent: boolean;
  skipReason?: string;
  completedAt?: string;
  completedBy?: string;
  notes?: string;
  createdAt: string;
  autoGenerated: boolean;
  generatedFrom?: {
    cropStage?: string;
    weatherCondition?: string;
    soilCondition?: string;
    pestRisk?: string;
  };
}

// ============= SCOUTING & ISSUE REPORTING (B4) =============

export type ScoutingCategory =
  | 'pest'
  | 'disease'
  | 'weed'
  | 'nutrient-deficiency'
  | 'water-stress'
  | 'lodging'
  | 'other';

export interface ScoutingPhoto {
  url: string;
  caption?: string;
  type: 'overview' | 'closeup' | 'leaf-front' | 'leaf-back' | 'root' | 'other';
}

export interface ScoutingRecord {
  id: string;
  fieldId: string;
  category: ScoutingCategory;
  severity: 1 | 2 | 3 | 4 | 5; // 1 = minor, 5 = critical
  affectedAreaPercent: number; // 0-100
  photos: ScoutingPhoto[];
  voiceNoteUrl?: string;
  notes: string;
  location?: { lat: number; lng: number };
  scoutedAt: string;
  scoutedBy?: string;
  
  // AI/Expert Response
  diagnosis?: {
    likelyIssues: {
      name: string;
      confidence: number; // 0-100
      description: string;
    }[];
    immediateActions: string[];
    safeAlternatives?: string[];
    whenToCallExpert: string;
    estimatedLoss?: number; // Expected yield loss %
    preventiveMeasures?: string[];
  };
}

// ============= INPUT APPLICATIONS LOG (B5) =============

export type ApplicationMethod = 'spray' | 'drench' | 'broadcast' | 'spot' | 'fertigation' | 'manual';

export interface FertilizerApplication {
  type: 'fertilizer';
  productName: string;
  nutrientContent: {
    nitrogen?: number;
    phosphorus?: number;
    potassium?: number;
    others?: string[];
  };
  dose: number; // kg/hectare
  method: ApplicationMethod;
  cost: number;
}

export interface PesticideApplication {
  type: 'pesticide' | 'fungicide' | 'herbicide' | 'insecticide';
  productName: string;
  activeIngredient: string;
  concentration: string;
  dilution: string; // e.g., "2ml/L"
  coverage: number; // hectares
  reEntryPeriod: number; // hours
  preHarvestInterval: number; // days
  cost: number;
}

export interface IrrigationEvent {
  type: 'irrigation';
  method: string;
  duration: number; // hours
  waterVolume?: number; // liters or cubic meters
  energyCost?: number;
}

export interface LaborMachineryEvent {
  type: 'labor' | 'machinery';
  activity: string;
  workers?: number;
  hours: number;
  machineryUsed?: string;
  fuelConsumed?: number; // liters
  cost: number;
}

export type InputApplication =
  | FertilizerApplication
  | PesticideApplication
  | IrrigationEvent
  | LaborMachineryEvent;

export interface InputApplicationLog {
  id: string;
  fieldId: string;
  cropId?: string;
  taskId?: string;
  application: InputApplication;
  appliedAt: string;
  appliedBy?: string;
  weatherConditions?: {
    temperature: number;
    humidity: number;
    windSpeed: number;
    rainfall: number;
  };
  notes?: string;
  photos?: string[];
  complianceStatus: 'compliant' | 'warning' | 'violation';
}

// ============= HARVEST & OUTPUT RECORDING (B6) =============

export interface HarvestRecord {
  id: string;
  fieldId: string;
  cropId: string;
  harvestDate: string;
  
  // Yield Data
  totalYield: number; // kg or quintal
  yieldPerHectare: number;
  moisturePercent: number;
  grade: 'A' | 'B' | 'C' | 'Reject';
  
  // Storage
  storageMethod: 'warehouse' | 'home' | 'farm' | 'cold-storage';
  bagCount?: number;
  storageLocation?: string;
  
  // Sale
  saleDate?: string;
  buyer?: string;
  mandi?: string;
  pricePerKg: number;
  totalRevenue: number;
  transportCost: number;
  otherCosts: number;
  netProfit: number;
  
  // Post-Harvest
  postHarvestAdvisories?: string[];
  qualityIssues?: string[];
  storageRisks?: string[];
  
  notes?: string;
}

// ============= CROP SIMULATOR (B7) =============

export interface SimulationInputs {
  cropType: string;
  variety: string;
  fieldId: string;
  sowingWindow: {
    start: string;
    end: string;
  };
  soilHealth: {
    organic: number; // 0-100
    nitrogen: number;
    phosphorus: number;
    potassium: number;
    ph: number;
  };
  waterAvailability: 'abundant' | 'adequate' | 'limited' | 'scarce';
  inputStrategy: 'low' | 'medium' | 'high';
  historicalWeather?: boolean; // Use historical weather data
}

export interface YieldEstimate {
  optimistic: number; // kg/hectare
  realistic: number;
  pessimistic: number;
  confidence: number; // 0-100
  factors: {
    soilContribution: number; // -20 to +20%
    waterContribution: number;
    inputContribution: number;
    weatherRisk: number;
    pestRisk: number;
  };
}

export interface TimelineSimulation {
  stage: string;
  startDate: string;
  endDate: string;
  durationDays: number;
  keyActivities: string[];
  riskWindows: {
    type: 'pest' | 'disease' | 'weather';
    name: string;
    probability: number; // 0-100
    impact: 'low' | 'medium' | 'high';
    mitigation: string[];
  }[];
}

export interface BudgetSimulation {
  strategy: 'low' | 'medium' | 'high';
  breakdown: {
    seeds: number;
    fertilizers: number;
    pesticides: number;
    irrigation: number;
    labor: number;
    machinery: number;
    other: number;
  };
  totalCost: number;
  expectedRevenue: {
    optimistic: number;
    realistic: number;
    pessimistic: number;
  };
  breakEvenPrice: number; // INR per kg
  roi: {
    optimistic: number; // %
    realistic: number;
    pessimistic: number;
  };
}

export interface CropSimulationResult {
  id: string;
  inputs: SimulationInputs;
  yieldEstimate: YieldEstimate;
  timeline: TimelineSimulation[];
  budget: BudgetSimulation;
  recommendations: {
    bestSowingDate: string;
    reason: string;
    alternativeDates?: string[];
  };
  districtComparison?: {
    districtName: string;
    averageYield: number;
    yourEstimate: number;
    difference: number; // %
  };
  riskAssessment: {
    overall: 'low' | 'medium' | 'high';
    factors: {
      name: string;
      level: 'low' | 'medium' | 'high';
      description: string;
    }[];
  };
  createdAt: string;
}

// ============= DASHBOARD SUMMARY =============

export interface FarmDashboardSummary {
  totalFields: number;
  activeFields: number;
  totalArea: number; // hectares
  averageHealthScore: number;
  pendingTasks: number;
  criticalTasks: number;
  activeScoutingIssues: number;
  upcomingHarvests: number;
  thisSeasonInvestment: number;
  projectedRevenue: number;
}
